name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - ipycanvas
  - numpy
  - matplotlib
  - pandas
  - scikit-learn
  - scipy
  - sqlite
  - bokeh
  - panel
  - altair
  - ipympl
  - vega_datasets
  - pyviz_comms
